version: "3.9"
services:
  dynamic-datasource:
    restart: always
    container_name: dynamic-datasource
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    environment:
      - TZ=Asia/Shanghai