server:
  port: 8088
spring:
  thymeleaf:
  cache: false
  mode: HTML5
  datasource:
    dynamic:
      primary: master
      p6spy: false
      strict: false
      datasource:
        sqLite:
          driver-class-name: org.sqlite.JDBC
          url: jdbc:sqlite::resource:sqlite/querySql.db
          username:
          password:
        master:
          url: jdbc:db2://160.0.1.19:50000/appdb
          username: db2inst1
          password: password
          driver-class-name: com.ibm.db2.jcc.DB2Driver
# 日志配置
logging:
  config: classpath:logback-spring.xml
