server:
  # ????????
  port: 8088
spring:
  thymeleaf:
  # ???????
  cache: false
  mode: HTML5
  datasource:
    dynamic:
      primary: master #??????????????,?????master
      p6spy: true
      strict: false #???????,??false. true?????????????,false???????
      datasource:
        master:
          url: jdbc:db2://160.0.1.19:50000/appdb
          username: db2inst1
          password: password
          driver-class-name: com.ibm.db2.jcc.DB2Driver # 3.2.0????SPI??????

